Name,SectionIdentifier__c,Url__c,AxiomAssetTags__c
AXIOMOMD: Action Registers,axiomomd__actionregisters,https://contextualtraining.axiomsfd.com/omd/activities.html,SSP2_DZONE_101_K_00000
AXIOMOMD: Business State & Gaps,axiomomd__businessstates,https://contextualtraining.axiomsfd.com/omd/business-state-and-gaps.html,"SSP2_BIZDEC_101_K_00000, SSP2_QMTG2_101_K_00000"
AXIOMOMD: Commonalities,axiomomd__commonalities,https://contextualtraining.axiomsfd.com/omd/commonalities.html,SSP2_INFOB_101_K_00000
AXIOMOMD: Current PSCF,axiomomd__currentpscf,https://contextualtraining.axiomsfd.com/omd/current-pscf.html,SSP2_QMTG4_101_K_00000
AXIOMOMD: Danger Zones,axiomomd__dangerzones,https://contextualtraining.axiomsfd.com/omd/danger-zones.html,SSP2_DZONE_101_K_00000
AXIOMOMD:: Decision Stages,axiomomd__decisionstages,https://contextualtraining.axiomsfd.com/omd/decision-stages.html,SSP2_QMTG7_101_K_00000
AXIOMOMD: Evaluators,axiomomd__evaluators,https://contextualtraining.axiomsfd.com/omd/evaluators-and-relationships.html,"SSP2_OMA_101_K_00000, SSP2_QMTG3_101_K_00000"
AXIOMOMD: Financial Criteria,axiomomd__financialcriteria,https://contextualtraining.axiomsfd.com/omd/financial-criteria.html,SSP2_QMTG5_101_K_00000
AXIOMOMD: PSC Criteria,axiomomd__psccriteria,https://contextualtraining.axiomsfd.com/omd/pcs-criteria.html,SSP2_QMTG4_101_K_00000
AXIOMOMD: Decision History,axiomomd__decisionhistory,https://contextualtraining.axiomsfd.com/omd/decision-history.html,SSP2_QMTG3_101_K_00000
