.evaluators .component-body .AXIOM_BASE__Alternatives__c {
	width: 16%;
}
.evaluators .component-body .AXIOM_BASE__Contact__c {
	width: 13%;
}
.evaluators .component-body .AXIOM_BASE__Contact__c .chzn-search {
	display: block;
}
.evaluators .component-body .AXIOM_BASE__Contact__c .ui-autocomplete {
	background: #FFFFFF;
}
.evaluators .component-body .AXIOM_BASE__Contact__c .ui-autocomplete li {
	margin: 0;
}
.evaluators .component-body .AXIOM_BASE__Contact__c .ui-autocomplete li .ui-state-hover {
	background: #2E76DA;
	border: none;
	color: white;
}
.evaluators .component-body .AXIOM_BASE__Contact__c .ui-autocomplete li a {
	color: black;
	cursor: pointer;
}
.evaluators .component-body .AXIOM_BASE__Influence__c {
	width: 12%;
}
.evaluators .Toggler {
	/*display : none;*/
}
.evaluators  .green {
	background-color : #d2e7d7 ;
}
.evaluators  .green.edit {
	background-color: #F4F4EE;
}
.evaluators .component-body select {
	width: 100%;
}
.pdf .evaluators .component-body .AXIOM_BASE__Influence__c {
	width: 8%;
}
.evaluators .component-body .AXIOM_BASE__Quality__c {
	width: 12%;
}
.pdf .evaluators .component-body .AXIOM_BASE__Quality__c {
	width: 8%;
}
.evaluators .component-body .AXIOM_BASE__Reason_Favored__c {
	width: 12%;
}
.pdf .evaluators .component-body .AXIOM_BASE__Reason_Favored__c {
	width: 14%;
}
.evaluators .component-body .AXIOM_BASE__Relationship_Notes__c {
	width: 15%;
}
.evaluators .component-body .AXIOM_BASE__Reports_To__c {
	width: 53%;
}
.evaluators .component-body .AXIOM_BASE__Roles__c {
	width: 30%;
}
.evaluators .component-body .Toggler {
	width: 3%;
}
.evaluators .component-body .alternative-field .picked-alternative {
	margin-top: 6px;
}
.evaluators .component-body .alternative-field .picked-alternative .star {
	background: url('/resource/axiom_base__images/icon-sprite.png') no-repeat -172px -32px;
	height: 12px;
	width: 13px;
}
.evaluators .component-body .alternative-field .picked-alternative .text {
	font-weight: bold;
}
.evaluators .component-body .custom-alternatives {
	margin-bottom: 4px;
}
.evaluators .component-body .roles-reports-wrapper {
	width: 17%;
}
.evaluators .component-body-item.edit .AXIOM_BASE__Roles__c {
	width: 87%;
}
.evaluators .component-body-item.edit .AXIOM_BASE__Reports_To__c {
	display: none;
}
.evaluators .component-header .evaluators-logo {
	background: url('/resource/axiom_base__images/icon-sprite.png') no-repeat;
}
.evaluators .component-body .modal-x {
	background: url('/resource/axiom_base__images/icon-sprite.png') no-repeat scroll -90px -32px transparent;
	cursor: pointer;
	height: 24px;
	width: 24px;
}
.evaluators .modal-header.component-header {
	background: #e5f2f6;
	background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIwJSIgeTI9IjEwMCUiPgogICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iI2U1ZjJmNiIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiNjZGU4ZjAiIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
	background: -moz-linear-gradient(top, #e5f2f6 0%, #cde8f0 100%);
	background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#e5f2f6), color-stop(100%,#cde8f0));
	background: -webkit-linear-gradient(top, #e5f2f6 0%,#cde8f0 100%);
	background: -o-linear-gradient(top, #e5f2f6 0%,#cde8f0 100%);
	background: -ms-linear-gradient(top, #e5f2f6 0%,#cde8f0 100%);
	background: linear-gradient(to bottom, #e5f2f6 0%,#cde8f0 100%);
	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#e5f2f6', endColorstr='#cde8f0',GradientType=0 );
	border-bottom: 1px solid #B9B9B9;
	border-top-left-radius: 6px;
	border-top-right-radius: 6px;
	-webkit-border-top-left-radius: 6px;
	-webkit-border-top-right-radius: 6px;
	-moz-border-radius-topleft: 6px;
	-moz-border-radius-topright: 6px;

	box-shadow: 0 1px 3px rgba(0,0,0,.17), inset 0 0 0px 1px white;
	-moz-box-shadow: 0 1px 3px rgba(0,0,0,.17), inset 0 0 0px 1px white;
	-webkit-box-shadow: 0 1px 3px rgba(0,0,0,.17), inset 0 0 0px 1px white;

	color: #000000;
	font-size: 14px;
	font-weight: bold;
	height: 32px;
	line-height: 32px;
	padding: 5px 20px;
	text-shadow: 0px 1px 0px #ffffff;
}
.evaluators .error_message .modal-header.component-header {
	color: #EF6262;
}
.evaluators .component-body .modal-x {
	width: 14px !important;
}
.evaluators .modal-body {
	padding: 15px 20px !important;
	font-size: 12px;
}