.financialCriteria .component-body .component-body-item .Buttons .view {
	display: none;
	left: 3px;
	position: absolute;
}
.financialCriteria .component-body .component-body-item:hover .Buttons .view {
	display: block;
}
.financialCriteria .component-body .component-body-item.edit:hover .Buttons .view {
	display: none;
}
.financialCriteria .component-body .AXIOM_BASE__BIO_Worksheet__c {
	width: 15%;
}
.financialCriteria .component-body .Financial_Considerations {
	width: 22%;
}
.financialCriteria .component-body .AXIOM_BASE__Budget__c {
	width: 16%;
}
.financialCriteria .component-body .Value_Assignment {
	text-align: center;
	width: 32%;
}
.financialCriteria .component-header .financialCriteria-logo {
	background: url('financialCriteria.png') no-repeat;
}
.financialCriteria .component-body .picked-primary {
	margin-top: 6px;
}
.financialCriteria .component-body .assignment-wrapper {
	width: 49%;
	float:left;
}
.financialCriteria .component-body .assignment-wrapper div {
	width: 50%;
	float:left;
}
.financialCriteria .component-body .assignment-wrapper input {
	margin: 2px;
}
.financialCriteria .component-body .assignment-wrapper div.label {
	text-align: right;
}
.financialCriteria .component-body .modal-x {
	background: url('x_gray.png') no-repeat scroll 0 9px transparent;
	cursor: pointer;
	height: 24px;
	width: 24px;
}
.financialCriteria .component-body .picked-primary .star {
	background: url('star.png') no-repeat;
	height: 12px;
	width: 13px;
}
.financialCriteria .component-body .picked-primary .text {
	font-weight: bold;
}
.financialCriteria .component-body-header .Status, .component-body-item .Status {
	width: 32px;
}
.financialCriteria .component-body-item .Status .minus, .component-body-item .Status .plus {
	cursor: pointer;
	height: 12px;
	margin: 1px;
	padding: 1px;
	width: 12px;
}
.financialCriteria .component-body-item .Status .plus {
	background: url('plus_gray.png') no-repeat scroll 0 0 transparent;
}
.financialCriteria .component-body-item .Status .minus {
	background: url('minus_gray.png') no-repeat scroll 0 0 transparent;
}
.financialCriteria .component-body-item .Status.minus .minus {
	background: url('minus.png') no-repeat scroll 0 0 transparent;
	display: block;
}
.financialCriteria .component-body-item .Status.plus .plus {
	background: url('plus.png') no-repeat scroll 0 0 transparent;
	display: block;
}

.financialCriteria  .modal-header.component-header {
	background: #e5f2f6;
	background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIwJSIgeTI9IjEwMCUiPgogICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iI2U1ZjJmNiIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiNjZGU4ZjAiIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
	background: -moz-linear-gradient(top, #e5f2f6 0%, #cde8f0 100%);
	background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#e5f2f6), color-stop(100%,#cde8f0));
	background: -webkit-linear-gradient(top, #e5f2f6 0%,#cde8f0 100%);
	background: -o-linear-gradient(top, #e5f2f6 0%,#cde8f0 100%);
	background: -ms-linear-gradient(top, #e5f2f6 0%,#cde8f0 100%);
	background: linear-gradient(to bottom, #e5f2f6 0%,#cde8f0 100%);
	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#e5f2f6', endColorstr='#cde8f0',GradientType=0 );
	border-bottom: 1px solid #B9B9B9;
	border-top-left-radius: 6px;
	border-top-right-radius: 6px;
	-webkit-border-top-left-radius: 6px;
	-webkit-border-top-right-radius: 6px;
	-moz-border-radius-topleft: 6px;
	-moz-border-radius-topright: 6px;

	box-shadow: 0 1px 3px rgba(0,0,0,.17), inset 0 0 0px 1px white;
	-moz-box-shadow: 0 1px 3px rgba(0,0,0,.17), inset 0 0 0px 1px white;
	-webkit-box-shadow: 0 1px 3px rgba(0,0,0,.17), inset 0 0 0px 1px white;

	color: #000000;
	font-size: 14px;
	font-weight: bold;
	height: 32px;
	line-height: 32px;
	padding: 5px 20px;
	text-shadow: 0px 1px 0px #ffffff;
}
.financialCriteria .error_message .modal-header.component-header {
	color: #EF6262;
}
.financialCriteria .component-body .modal-x {
	width: 14px !important;
}
.financialCriteria  .modal-body {
	padding: 15px 20px !important;
	font-size: 12px;
}