Name,SectionIdentifier__c,Url__c,AxiomAssetTags__c
AXIOM_LC:Metrics,axiom_lc__metrics,https://contextualtraining.axiomsfd.com/success-plans/metrics-review.html,"SSM_GoalSet_101_K_00000, SSM_UnGap_101_K_00000, SSM_RootC_101_K_00000"
AXIOM_LC:Peoples,axiom_lc__peoples,https://contextualtraining.axiomsfd.com/success-plans/people.html,
AXIOM_LC:Opportunity Review,axiom_lc__opportunity_review,https://contextualtraining.axiomsfd.com/success-plans/opportunity-list.html,"SSM_UnGap_101_K_00000, SSM_RootC_101_K_00000"
AXIOM_LC:Account Plan Review,axiom_lc__accountplan_review,https://contextualtraining.axiomsfd.com/success-plans/account-plan.html,
AXIOM_LC:Field Observations,axiom_lc__field_observation,https://contextualtraining.axiomsfd.com/success-plans/field-observations.html,"SSM_DefAsgn_101_K_00000, SSM_EvalP_101_K_00000"
AXIOM_LC:Assignments,axiom_lc__assignments,https://contextualtraining.axiomsfd.com/success-plans/assignments.html,"SSM_DefAsgn_101_K_00000, SSM_EvalP_101_K_00000"
